name: Publish Playwright Report

on:
  release:
    types: [published]

permissions:
  contents: write

jobs:
  publish-report:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        id: tests
        continue-on-error: true
        run: npx playwright test

      - name: Publish Playwright HTML report
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: playwright-report
          destination_dir: releases/${{ github.event.release.tag_name }}
          keep_files: true

      - name: Fail workflow if tests failed
        if: steps.tests.outcome == 'failure'
        run: exit 1
